#!/bin/sh

## SPDX-FileCopyrightText: 2023 Benjamin Grande M. S. <ben.grande.b@gmail.com>
##
## SPDX-License-Identifier: AGPL-3.0-or-later

## Credits: git/contrib/git-shell-commands/help

set -eu

printf "Available commands:\n"
for f in "${0%/*}"/*; do
  test "${f##*/}" != "help" || continue
  test -f "${f}" || continue
  test -x "${f}" || continue
  usage="$("${f}" --help 2>&1 | head -1 | sed "s/[Uu]sage: //")"
  printf ' %-15s\t\t%s\n' "${f##*/}" "${usage}"
done
