#!/bin/sh

## SPDX-FileCopyrightText: 2004 - 2022 Tim Pope <https://tpo.pe>
## SPDX-FileCopyrightText: 2023 Benjamin Grande M. S. <ben.grande.b@gmail.com>
##
## SPDX-License-Identifier: AGPL-3.0-or-later

# shellcheck disable=SC1090,SC1091

if test -z "${ENV}" && test -n "${PATH}"; then
  case $- in
    *l*) ;;
      *) . "${HOME}/.bash_profile" >/dev/null ;;
  esac
fi
