#!/bin/sh

## SPDX-FileCopyrightText: 2023 Benjamin Grande M. S. <ben.grande.b@gmail.com>
##
## SPDX-License-Identifier: AGPL-3.0-or-later

# shellcheck disable=SC1090,1091

. "${HOME}/.profile"
case $- in
  *i*) . "${HOME}/.bashrc";;
  *) ;;
esac
